### ISSUE TITLE
fix: The web version on mobile device is not displayed properly

### ISSUE THREAD

**Issue by lambej** [VeryGoodOpenSource/very_good_flame_game#145]
**Description**
I tried the web build on a mobile device. The text is too big for the screen and the image is blurry.

**Steps To Reproduce**

1. Build the project `flutter build web -t lib/main_production.dart`
2. Deploy on firebase
3. Go to your app on your mobile browser

**Expected Behavior**
I'm expecting the game to be optimized for mobile devices even if it's the web version.

**Screenshots**
![image](https://github.com/VeryGoodOpenSource/very_good_flame_game/assets/81495719/39d8d938-787b-4772-ae06-9b40de6308e0)

**Comment by wolfenrain** [comment]
We probably have to change the [TextComponent](https://github.com/VeryGoodOpenSource/very_good_flame_game/blob/main/src/very_good_flame_game/lib/game/components/counter_component.dart#L10) to be a TextBoxComponent that knows the max width so it wraps correctly.

If you feel up to it you can have a stab at it yourself!

**Comment by lambej** [comment]
Yes why not, I can give it a try :)

**Comment by lambej** [comment]
I would need some help for that. I changed the `TextComponent` for a `TextBoxComponent` but I still not see the text correctly. It still too big for the screen.

**Comment by alestiago** [comment]
HI @lambej ! We can try helping you out 🙌 

In the meantime, we're moving this repository to [Very Good Templates](https://github.com/VeryGoodOpenSource/very_good_templates). Hence, I'm closing this issue. Could you re-open the issue there?
