### ISSUE TITLE
fix: create a Floor or platforms class in Flame Game so that it is easier to build a vertical scrolling game

### ISSUE THREAD

**Issue by Genius19245** [VeryGoodOpenSource/very_good_flame_game#72]
**Description**

**Steps To Reproduce**

**Expected Behavior**

**Screenshots**

**Additional Context**

**Comment by renancaraujo** [comment]
Hello, this sounds a bit outside the scope of this template. 

In the conception of this, we discussed which features the template should include. As this is meant as a bare starter for Flame projects, we decided to include only structural code (loading assets, tests, etc) to keep the template unbiased, as games tend to change a lot given what game you are building. 


However, if you need help with that specific type of game, I suggest looking into some flame resources like the [awesome list](https://github.com/flame-engine/awesome-flame) and the [Doodle dash challenge ](https://flutter.dev/events/doodle-dash-challenge) which is pretty close to what you are describing.
